package com.boxnotfound.tictactoe.game;

import android.content.Context;
import android.os.Bundle;
import android.util.AttributeSet;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.BaseAdapter;
import android.widget.GridView;

import com.boxnotfound.tictactoe.R;
import com.boxnotfound.tictactoe.model.TicTacToeTile;
import com.boxnotfound.tictactoe.model.TileColor;
import com.boxnotfound.tictactoe.model.TileStatus;
import com.boxnotfound.tictactoe.model.wincondition.WinCondition;

import java.util.List;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.appcompat.widget.AppCompatImageView;
import androidx.fragment.app.Fragment;

/**The View Component of the TicTacToe game board */
public class GameFragment extends Fragment implements GameContract.View {

    /** Reference to the Presenter component responsible for handling UI updates. */
    private GameContract.Presenter presenter;
    /** The Adapter responsible for managing the UI of the {@link #gameBoardView} */
    private GameBoardAdapter adapter;
    /** The parent Activity, which receives communications from the Fragment through the
     * {@link OnGameUpdateListener} interface.
     * */
    private OnGameUpdateListener gameUpdateListener;
    /** The primary UI component for the game board */
    private GridView gameBoardView;

    @Override
    public void onAttach(Context context) {
        super.onAttach(context);
        // We need the parent Activity to implement OnGameUpdateListener so we can communicate
        // UI updates from the Fragment to the Activity
        if (context instanceof OnGameUpdateListener) {
            gameUpdateListener = (OnGameUpdateListener) context;
        } else {
            throw new ClassCastException(context.toString() + " must implement OnPlayerTurnChangedListener");
        }
    }

    @Override
    public void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
    }

    @Nullable
    @Override
    public View onCreateView(@NonNull LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        return inflater.inflate(R.layout.fragment_game, container, false);
    }

    @Override
    public void onViewCreated(@NonNull View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        gameBoardView = view.findViewById(R.id.layout_game_board);
        adapter = new GameBoardAdapter();
        gameBoardView.setAdapter(adapter);
    }

    @Override
    public void onDetach() {
        super.onDetach();
        gameUpdateListener = null;
    }

    @Override
    public void onResume() {
        super.onResume();
        presenter.launchNewTicTacToeGame(false);
    }

    /**
     * Prepares the TicTacToe Game Board GridView by updating the GridView's numColumns parameter
     * to the user requested size and passes the list of {@linkplain TicTacToeTile TicTacToeTiles} to the GridView's
     * {@link GameBoardAdapter}.
     * @param tiles The list of TicTacToeTiles generated by {@link GamePresenter#setupTileListForView()}
     *              to be used to display the current game's state.
     * @param rowSize The number of columns the GridView should be set to to form an even square shape.
     */
    @Override
    public void displayNewTicTacToeGame(@NonNull final List<TicTacToeTile> tiles, final int rowSize) {
        gameBoardView.setNumColumns(rowSize);
        adapter.setTiles(tiles);
    }

    /**
     * Called by the presenter after a {@link TicTacToeTile} state change has occurred as a result
     * of a player move in order to keep the Game Board GridView UI up-to-date.
     */
    @Override
    public void displayPlayerMove() {
        adapter.notifyDataSetChanged();
    }

    /**
     * Called by the presenter following a player move to update the UI to show that it is now
     * the next player's turn to make a move.
     * @param player The {@linkplain TileStatus player} who will be making the next game move.
     */
    @Override
    public void displayPlayerTurn(@NonNull final TileStatus player) {
        // communicate this to the activity, since the current player turn UI exists there
        gameUpdateListener.onPlayerTurnChanged(player);
    }

    /**
     * Called by the presenter following a call to {@link WinCondition#winConditionMet()}
     * returning true, indicating that the game is over and has been won.
     * @param winningPlayer The {@link TileStatus} winning player that has fulfilled the requirements
     *                      of a game board {@link WinCondition}.
     */
    @Override
    public void displayGameWon(@NonNull final TileStatus winningPlayer) {
        adapter.notifyDataSetChanged();
        gameUpdateListener.onPlayerWin(winningPlayer);
    }

    /**
     * Called by the presenter when the game board has been filled without any
     * {@link WinCondition#winConditionMet()} returning true, resulting in a draw.
     */
    @Override
    public void displayGameDraw() {
        gameUpdateListener.onDraw();
    }

    /**
     * Hold a reference to the {@link GameContract.Presenter presenter} component.
     * @param presenter
     */
    @Override
    public void setPresenter(@NonNull GameContract.Presenter presenter) {
        this.presenter = presenter;
    }

    /**
     * The GameBoardAdapter class is responsible for managing the state of the
     * Game Board GridView UI.
     */
    private class GameBoardAdapter extends BaseAdapter {

        private List<TicTacToeTile> tiles;

        /**
         * Stores the list of {@linkplain TicTacToeTile TicTacToeTiles} representing
         * the current game state.
         * @param tiles The list of {@linkplain TicTacToeTile TicTacToeTiles} generated
         *              by the {@link GamePresenter#setupTileListForView()} method.
         */
        public void setTiles(@NonNull final List<TicTacToeTile> tiles) {
            this.tiles = tiles;
            notifyDataSetChanged();
        }

        @Override
        public int getCount() {
            if (tiles == null) {
                return 0;
            } else {
                return tiles.size();
            }
        }

        @Override
        public Object getItem(int position) {
            return null;
        }

        @Override
        public long getItemId(int position) {
            return 0;
        }

        /**
         * Takes each {@link TicTacToeTile} from the cached list displays the appropriate
         * UI state for each as determined by their respective {@link TileStatus} and
         * {@link TileColor} states.
         * @param position GridView adapter position
         * @param convertView Inflated Game Tile Item View
         * @param parent Parent View
         * @return The updated UI item state.
         */
        @Override
        public View getView(int position, View convertView, ViewGroup parent) {
            TicTacToeTile tile = tiles.get(position);
            TileStatus currentState = tile.getCurrentState();
            TileColor currentColor = tile.getCurrentColor();

            if (convertView == null) {
                final LayoutInflater layoutInflater = LayoutInflater.from(getContext());
                convertView = layoutInflater.inflate(R.layout.game_tile_item, parent, false);
            }

            TileImageView tileImage = convertView.findViewById(R.id.iv_game_tile);

            if (currentState == TileStatus.PLAYER_O) {
                tileImage.setImageResource(R.drawable.ic_player_o);
            } else if (currentState == TileStatus.PLAYER_X) {
                tileImage.setImageResource(R.drawable.ic_player_x);
            } else {
                tileImage.setImageResource(android.R.color.transparent);
            }

            if (currentColor == TileColor.PREVIOUS_MOVE) {
                tileImage.setColorFilter(getResources().getColor(R.color.colorTilePreviousMove));
            } else if (currentColor == TileColor.WINNER) {
                tileImage.setColorFilter(getResources().getColor(R.color.colorTileWinner));
            } else {
                tileImage.setColorFilter(getResources().getColor(R.color.colorTileNormal));
            }

            tileImage.setOnClickListener(v -> presenter.setPlayerMove(position));

            return tileImage;
        }
    }

    /**
     * Custom ImageView class whose responsibility is primarily to setup each GridView
     * ImageView item to be an equal square shape by overriding the onMeasure method
     * and passing the width parameter as both parameters to the super class call.
     */
    public static class TileImageView extends AppCompatImageView {

        public TileImageView(Context context) {
            super(context);
        }

        public TileImageView(Context context, @Nullable AttributeSet attrs) {
            super(context, attrs);
        }

        public TileImageView(Context context, @Nullable AttributeSet attrs, int defStyleAttr) {
            super(context, attrs, defStyleAttr);
        }

        @Override
        protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {
            // Pass in the width to both super parameters to ensure a square shape
            super.onMeasure(widthMeasureSpec, widthMeasureSpec);
        }
    }

    /**
     * The primary interface used for communications from the {@link GameFragment} to the
     * {@link GameActivity}.
     */
    public interface OnGameUpdateListener {
        void onPlayerTurnChanged(@NonNull final TileStatus player);

        void onPlayerWin(@NonNull final TileStatus player);

        void onDraw();
    }
}
